#!/usr/bin/env python3
"""
Generate Log Categories Header + Implementation
================================================
Reads taxonomy JSON files and generates C++ header AND implementation.

Usage:
    python core/core/ase-log/scripts/gen_log_cat.py

Output:
    core/core/ase-log/include/ase/log/log_cat_gen.hpp  (~3KB - declarations only)
    core/core/ase-log/src/log_cat_gen.cpp              (~500KB - implementations)

The header is small and safe to include everywhere.
The big switch (7144 cases) is compiled ONCE in the .cpp.
"""

import json
import sys
from pathlib import Path
from typing import Dict, Set


def load_all_abbreviations(taxonomy_dir: Path) -> Dict[str, int]:
    """Load ALL abbreviations from taxonomy files and assign bit positions."""
    abbrevs: Set[str] = set()

    # Load from _index.json first (top-level categories)
    index_file = taxonomy_dir / "_index.json"
    if index_file.exists():
        with open(index_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            for cat in data.get('categories', []):
                abbrevs.add(cat['abbrev'].upper())

    # Load from individual taxonomy files (ALL nested abbreviations)
    for f in taxonomy_dir.glob("*.json"):
        if f.name.startswith('_'):
            continue
        try:
            with open(f, 'r', encoding='utf-8') as fp:
                data = json.load(fp)
                extract_abbrevs_recursive(data, abbrevs)
        except Exception as e:
            print(f"Warning: Failed to parse {f}: {e}", file=sys.stderr)

    # Sort and assign bit positions (NO LIMIT - scales to any number!)
    sorted_abbrevs = sorted(abbrevs)
    return {abbrev: i for i, abbrev in enumerate(sorted_abbrevs)}


def extract_abbrevs_recursive(node: dict, abbrevs: Set[str]) -> None:
    """Recursively extract ALL abbreviations from taxonomy node."""
    if not isinstance(node, dict):
        return

    for key, value in node.items():
        # Skip metadata
        if key in ('name', 'description', '_schema_version') and isinstance(value, str):
            continue

        # Extract from 'nouns' dict - ALL of them
        if key == 'nouns' and isinstance(value, dict):
            for noun_abbrev in value.values():
                if len(noun_abbrev) >= 2:
                    abbrevs.add(noun_abbrev.upper())
            continue

        # The key itself might be an abbreviation (2-4 chars)
        if 2 <= len(key) <= 4 and key not in ('children', 'nouns', 'type', 'name'):
            abbrevs.add(key.upper())

        # Recurse into everything
        if isinstance(value, dict):
            extract_abbrevs_recursive(value, abbrevs)


def fnv1a_hash(s: str) -> int:
    """Calculate FNV-1a hash (same as C++ implementation)."""
    h = 2166136261
    for c in s.lower():
        h = ((h ^ ord(c)) * 16777619) & 0xFFFFFFFF
    return h


def generate_header(abbrev_bits: Dict[str, int], output_path: Path) -> bool:
    """Generate the small C++ header file (declarations only).

    Returns True if file was changed.
    """
    num_categories = len(abbrev_bits)
    num_chunks = (num_categories + 63) // 64

    lines = [
        '#pragma once',
        '',
        '/**',
        ' * AUTO-GENERATED FILE - DO NOT EDIT!',
        ' * ',
        ' * Generated by: core/core/ase-log/scripts/gen_log_cat.py',
        ' * Source: core/core/ase-validator/ecs_validator/data/taxonomy/*.json',
        ' * ',
        ' * SMALL HEADER - safe to include everywhere.',
        ' * Big switch (7144 cases) is in log_cat_gen.cpp.',
        ' * ',
        f' * Total categories: {num_categories}',
        f' * Bit-array chunks: {num_chunks} (64 bits each)',
        ' */',
        '',
        '#include <atomic>',
        '#include <cstdint>',
        '',
        'namespace ase::log::filter {',
        '',
        '// ============================================================================',
        '// Constants',
        '// ============================================================================',
        '',
        f'constexpr int CATEGORY_COUNT = {num_categories};',
        f'constexpr int CHUNK_COUNT = {num_chunks};',
        '',
        '// ============================================================================',
        '// Log Levels (bitmask)',
        '// ============================================================================',
        '',
        'constexpr uint8_t LVL_TRC = 0x01;  // Trace',
        'constexpr uint8_t LVL_DBG = 0x02;  // Debug',
        'constexpr uint8_t LVL_INF = 0x04;  // Info',
        'constexpr uint8_t LVL_WRN = 0x08;  // Warn',
        'constexpr uint8_t LVL_ERR = 0x10;  // Error',
        'constexpr uint8_t LVL_CRT = 0x20;  // Critical',
        'constexpr uint8_t LVL_ALL = 0x3F;  // All levels',
        '',
        '// ============================================================================',
        '// Category Bit-Array (scalable to unlimited categories)',
        '// ============================================================================',
        '',
        'struct CategoryMask {',
        '    uint64_t chunks[CHUNK_COUNT] = {};',
        '    ',
        '    void set(int bit_pos);',
        '    bool intersects(const CategoryMask& other) const;',
        '};',
        '',
        '// ============================================================================',
        '// Runtime Filter State (defined in log_cat_gen.cpp)',
        '// ============================================================================',
        '',
        'extern std::atomic<uint8_t> g_level_mask;',
        'extern CategoryMask g_blocked_categories;',
        '',
        '// ============================================================================',
        '// Client Filter State (defined in log_cat_gen.cpp)',
        '// ============================================================================',
        '',
        'extern std::atomic<uint64_t> g_client_mask;      ///< Whitelist (0 = all pass)',
        'extern std::atomic<uint64_t> g_blocked_clients;   ///< Blacklist bitmask',
        '',
        '// ============================================================================',
        '// Function Declarations (implemented in log_cat_gen.cpp)',
        '// ============================================================================',
        '',
        '/// Hash abbreviation to bit position (-1 if not found)',
        'int abbrev_to_bit(uint32_t hash);',
        '',
        '/// Extract categories from filename',
        'CategoryMask file_to_categories(const char* file);',
        '',
        '/// Check if log should be emitted',
        'bool should_log(uint8_t level, const CategoryMask& file_cats);',
        '',
        '/// Check if client log should be emitted (level + category + client filter)',
        'bool should_log_client(uint8_t level, const CategoryMask& file_cats, uint64_t client_bit);',
        '',
        '/// Parse CLI filter string (e.g., "+INF +WRN -BCT +CLT:01")',
        'void parse_log_filter(const char* filter_str);',
        '',
        '}  // namespace ase::log::filter',
        '',
    ]

    new_content = '\n'.join(lines)
    return write_if_changed(output_path, new_content)


def generate_impl(abbrev_bits: Dict[str, int], output_path: Path) -> bool:
    """Generate the large C++ implementation file.

    Returns True if file was changed.
    """
    num_categories = len(abbrev_bits)

    lines = [
        '/**',
        ' * AUTO-GENERATED FILE - DO NOT EDIT!',
        ' * ',
        ' * Generated by: core/core/ase-log/scripts/gen_log_cat.py',
        ' * Source: core/core/ase-validator/ecs_validator/data/taxonomy/*.json',
        ' * ',
        ' * This file contains the big switch (7144 cases).',
        ' * Compiled ONCE, not in every translation unit.',
        ' */',
        '',
        '#include <ase/log/log_cat_gen.hpp>',
        '#include <cstring>',
        '',
        'namespace ase::log::filter {',
        '',
        '// ============================================================================',
        '// Runtime Filter State (definitions)',
        '// ============================================================================',
        '',
        'std::atomic<uint8_t> g_level_mask{LVL_ALL};',
        'CategoryMask g_blocked_categories{};',
        'std::atomic<uint64_t> g_client_mask{0};',
        'std::atomic<uint64_t> g_blocked_clients{0};',
        '',
        '// ============================================================================',
        '// CategoryMask Implementation',
        '// ============================================================================',
        '',
        'void CategoryMask::set(int bit_pos) {',
        '    if (bit_pos >= 0 && bit_pos < CATEGORY_COUNT) {',
        '        chunks[bit_pos / 64] |= (1ULL << (bit_pos % 64));',
        '    }',
        '}',
        '',
        'bool CategoryMask::intersects(const CategoryMask& other) const {',
        '    for (int i = 0; i < CHUNK_COUNT; ++i) {',
        '        if (chunks[i] & other.chunks[i]) return true;',
        '    }',
        '    return false;',
        '}',
        '',
        '// ============================================================================',
        '// Category Bit Positions (auto-generated from taxonomy)',
        '// ============================================================================',
        '',
    ]

    # Generate category bit position constants (in .cpp, not header!)
    for abbrev, bit_pos in sorted(abbrev_bits.items(), key=lambda x: x[1]):
        lines.append(f'constexpr int BIT_{abbrev} = {bit_pos};')

    lines.extend([
        '',
        '// ============================================================================',
        '// Hash to Bit Position Lookup (the big switch)',
        '// ============================================================================',
        '',
        'namespace {',
        '',
        'constexpr char to_lower(char c) {',
        '    return (c >= \'A\' && c <= \'Z\') ? static_cast<char>(c + 32) : c;',
        '}',
        '',
        'constexpr uint32_t hash_part(const char* start, const char* end) {',
        '    uint32_t hash = 2166136261u;',
        '    for (const char* p = start; p < end; ++p) {',
        '        char c = to_lower(*p);',
        '        hash = (hash ^ static_cast<uint32_t>(c)) * 16777619u;',
        '    }',
        '    return hash;',
        '}',
        '',
        'const char* find_filename(const char* path) {',
        '    const char* result = path;',
        '    for (const char* p = path; *p; ++p) {',
        '        if (*p == \'/\' || *p == \'\\\\\') result = p + 1;',
        '    }',
        '    return result;',
        '}',
        '',
        '}  // anonymous namespace',
        '',
        'int abbrev_to_bit(uint32_t hash) {',
        '    switch (hash) {',
    ])

    # Generate hash-to-bit-position mapping (THE BIG SWITCH)
    for abbrev, bit_pos in sorted(abbrev_bits.items()):
        hash_val = fnv1a_hash(abbrev)
        lines.append(f'        case {hash_val}u: return BIT_{abbrev};  // "{abbrev.lower()}"')

    lines.extend([
        '        default: return -1;',
        '    }',
        '}',
        '',
        '// ============================================================================',
        '// Filename to Categories',
        '// ============================================================================',
        '',
        'CategoryMask file_to_categories(const char* file) {',
        '    CategoryMask mask{};',
        '    const char* name = find_filename(file);',
        '    const char* part_start = name;',
        '    ',
        '    for (const char* p = name; ; ++p) {',
        '        if (*p == \'_\' || *p == \'.\' || *p == \'\\0\') {',
        '            if (p > part_start) {',
        '                uint32_t h = hash_part(part_start, p);',
        '                int bit = abbrev_to_bit(h);',
        '                if (bit >= 0) mask.set(bit);',
        '            }',
        '            if (*p == \'\\0\' || *p == \'.\') break;',
        '            part_start = p + 1;',
        '        }',
        '    }',
        '    return mask;',
        '}',
        '',
        '// ============================================================================',
        '// Runtime Filter Check',
        '// ============================================================================',
        '',
        'bool should_log(uint8_t level, const CategoryMask& file_cats) {',
        '    if (!(level & g_level_mask.load(std::memory_order_relaxed))) return false;',
        '    if (file_cats.intersects(g_blocked_categories)) return false;',
        '    return true;',
        '}',
        '',
        'bool should_log_client(uint8_t level, const CategoryMask& file_cats, uint64_t client_bit) {',
        '    if (!(level & g_level_mask.load(std::memory_order_relaxed))) return false;',
        '    if (file_cats.intersects(g_blocked_categories)) return false;',
        '    if (client_bit) {',
        '        if (client_bit & g_blocked_clients.load(std::memory_order_relaxed)) return false;',
        '        uint64_t mask = g_client_mask.load(std::memory_order_relaxed);',
        '        if (mask && !(client_bit & mask)) return false;',
        '    }',
        '    return true;',
        '}',
        '',
        '// ============================================================================',
        '// CLI Argument Parser',
        '// ============================================================================',
        '',
        'namespace {',
        '',
        'void parse_client_ids(const char* ids, std::atomic<uint64_t>& target) {',
        '    while (*ids) {',
        '        int id = 0;',
        '        while (*ids >= \'0\' && *ids <= \'9\') { id = id * 10 + (*ids - \'0\'); ids++; }',
        '        if (id >= 0 && id < 64) {',
        '            uint64_t old_val = target.load(std::memory_order_relaxed);',
        '            target.store(old_val | (1ULL << id), std::memory_order_relaxed);',
        '        }',
        '        if (*ids == \',\') ids++;',
        '        else break;',
        '    }',
        '}',
        '',
        'void parse_filter_token(const char* token) {',
        '    if (!token || !*token) return;',
        '    ',
        '    char op = token[0];',
        '    const char* code = token + 1;',
        '    ',
        '    if (op == \'+\') {',
        '        // +CLT:01 or +CLT:01,03 → client whitelist',
        '        if (std::strncmp(code, "CLT:", 4) == 0) {',
        '            parse_client_ids(code + 4, g_client_mask);',
        '            return;',
        '        }',
        '        // +CLT → all clients in whitelist',
        '        if (std::strcmp(code, "CLT") == 0) {',
        '            g_client_mask.store(0xFFFFFFFFFFFFFFFFULL, std::memory_order_relaxed);',
        '            return;',
        '        }',
        '        // +LEVEL',
        '        if (std::strcmp(code, "TRC") == 0) g_level_mask.fetch_or(LVL_TRC);',
        '        else if (std::strcmp(code, "DBG") == 0) g_level_mask.fetch_or(LVL_DBG);',
        '        else if (std::strcmp(code, "INF") == 0) g_level_mask.fetch_or(LVL_INF);',
        '        else if (std::strcmp(code, "WRN") == 0) g_level_mask.fetch_or(LVL_WRN);',
        '        else if (std::strcmp(code, "ERR") == 0) g_level_mask.fetch_or(LVL_ERR);',
        '        else if (std::strcmp(code, "CRT") == 0) g_level_mask.fetch_or(LVL_CRT);',
        '    } else if (op == \'-\') {',
        '        // -CLT → block all clients',
        '        if (std::strcmp(code, "CLT") == 0) {',
        '            g_blocked_clients.store(0xFFFFFFFFFFFFFFFFULL, std::memory_order_relaxed);',
        '            return;',
        '        }',
        '        // -CLT:05 or -CLT:05,07 → block specific clients',
        '        if (std::strncmp(code, "CLT:", 4) == 0) {',
        '            parse_client_ids(code + 4, g_blocked_clients);',
        '            return;',
        '        }',
        '        // -CATEGORY',
        '        uint32_t hash = 2166136261u;',
        '        for (const char* p = code; *p; ++p) {',
        '            char c = (*p >= \'A\' && *p <= \'Z\') ? static_cast<char>(*p + 32) : *p;',
        '            hash = (hash ^ static_cast<uint32_t>(c)) * 16777619u;',
        '        }',
        '        int bit = abbrev_to_bit(hash);',
        '        if (bit >= 0) g_blocked_categories.set(bit);',
        '    }',
        '}',
        '',
        '}  // anonymous namespace',
        '',
        'void parse_log_filter(const char* filter_str) {',
        '    if (!filter_str) return;',
        '    ',
        '    // Check if any +LEVEL token is present (skip +CLT which is client filter)',
        '    bool has_level = false;',
        '    for (const char* p = filter_str; *p; ++p) {',
        '        if (*p == \'+\' && std::strncmp(p + 1, "CLT", 3) != 0) {',
        '            has_level = true; break;',
        '        }',
        '    }',
        '    if (has_level) g_level_mask.store(0);',
        '    ',
        '    char token[128];',
        '    int ti = 0;',
        '    for (const char* p = filter_str; ; ++p) {',
        '        if (*p == \' \' || *p == \'\\0\') {',
        '            if (ti > 0) {',
        '                token[ti] = \'\\0\';',
        '                parse_filter_token(token);',
        '                ti = 0;',
        '            }',
        '            if (*p == \'\\0\') break;',
        '        } else if (ti < 127) {',
        '            token[ti++] = *p;',
        '        }',
        '    }',
        '}',
        '',
        '}  // namespace ase::log::filter',
        '',
    ])

    new_content = '\n'.join(lines)
    return write_if_changed(output_path, new_content)


def write_if_changed(path: Path, content: str) -> bool:
    """Write file only if content changed. Returns True if changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        old_content = path.read_text(encoding='utf-8')
        if old_content == content:
            return False

    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    return True


def main():
    script_dir = Path(__file__).parent  # ase-log/scripts/
    ase_log_dir = script_dir.parent     # ase-log/
    project_root = ase_log_dir.parent.parent.parent  # ase/ (up from core/core/ase-log)

    taxonomy_dir = project_root / "core" / "core" / "ase-validator" / "ecs_validator" / "data" / "taxonomy"
    header_path = ase_log_dir / "include" / "ase" / "log" / "log_cat_gen.hpp"
    impl_path = ase_log_dir / "src" / "log_cat_gen.cpp"

    if not taxonomy_dir.exists():
        print(f"Error: Taxonomy directory not found: {taxonomy_dir}", file=sys.stderr)
        sys.exit(1)

    abbrev_bits = load_all_abbreviations(taxonomy_dir)
    num_categories = len(abbrev_bits)

    header_changed = generate_header(abbrev_bits, header_path)
    impl_changed = generate_impl(abbrev_bits, impl_path)

    if header_changed or impl_changed:
        print(f"Generated: {header_path.name} + {impl_path.name}")
        print(f"Categories: {num_categories}")
    else:
        print(f"Unchanged: {header_path.name} + {impl_path.name}")
        print(f"Categories: {num_categories} (no rebuild needed)")


if __name__ == '__main__':
    main()
