/**
 * ASE CORE INFRASTRUCTURE IMPLEMENTATION
 *
 * AUTO-GENERATED FILE - DO NOT EDIT!
 * Edit core/ase-log/data/log_categories.json and run
 * core/ase-log/scripts/gen_log_cat.py instead. A hand fix here survives
 * exactly until the next generator run.
 *
 * @file        log_err_cat_gen.cpp
 * @brief       Name, help, short and suffix lookups for ERR::CAT and WRN::CAT
 * @description Each function matches the name hash it was given and returns the
 *              text that belongs to it. A hash that is NOT in the SSOT gets a
 *              LOUD marker, never the first entry: falling back to a real
 *              category would print a plausible wrong help text, and a reader who
 *              sees a valid-looking category does not check it. Kept in one
 *              translation unit so a changed help text recompiles this file,
 *              not the tree.
 *
 * @module      ase-log
 * @layer       1 (Core)
 * @category    ecs/module
 * @created     2026-08-23
 * @modified    2026-08-23
 * @version     1.0.0
 *
 * CORE INFRASTRUCTURE IMPLEMENTATION COMPLIANCE
 *
 * [ ] NOT an ECS System implementation
 * [ ] Layer dependencies correct (L0: no ASE deps, L1: L0 only)
 * [ ] Own header included FIRST
 * [ ] No global mutable state
 * [ ] No static initialization order fiasco
 * [ ] Thread-safe implementations (pure or mutex-protected)
 * [ ] All error conditions handled
 * [ ] No exceptions thrown (use Result<T> pattern)
 * [ ] Implementation details in anonymous namespace
 * [ ] No inline implementations of template specializations here
 * [ ] Platform-specific code isolated and documented
 * [ ] Performance-critical code profiled and optimized
 *
 * Generated by: core/ase-log/scripts/gen_log_cat.py
 * Source: core/ase-log/data/log_categories.json
 */

#include <ase/log/log_err_cat_gen.hpp>

namespace ase::log::detail {

const char* get_cat_name(uint32_t cat) {
    if (cat == ERR::CAT::UNKNOWN) {
        return "\x1b[38;2;215;95;95mUNKNOWN\x1b[0m";
    }
    if (cat == ERR::CAT::HUB_NOT_FOUND) {
        return "\x1b[38;2;215;95;95mHUB_NOT_FOUND\x1b[0m";
    }
    if (cat == ERR::CAT::HUB_GLOBAL_MISSING) {
        return "\x1b[38;2;215;95;95mHUB_GLOBAL_MISSING\x1b[0m";
    }
    if (cat == ERR::CAT::COMPONENT_MISSING) {
        return "\x1b[38;2;215;95;95mCOMPONENT_MISSING\x1b[0m";
    }
    if (cat == ERR::CAT::MANAGER_ABSENT) {
        return "\x1b[38;2;215;95;95mMANAGER_ABSENT\x1b[0m";
    }
    if (cat == ERR::CAT::INVALID_ENTITY) {
        return "\x1b[38;2;215;95;95mINVALID_ENTITY\x1b[0m";
    }
    if (cat == ERR::CAT::SCHEDULE_ORDER) {
        return "\x1b[38;2;215;95;95mSCHEDULE_ORDER\x1b[0m";
    }
    if (cat == ERR::CAT::CONFIG_MISSING) {
        return "\x1b[38;2;215;95;95mCONFIG_MISSING\x1b[0m";
    }
    if (cat == ERR::CAT::RESOURCE_UNAVAIL) {
        return "\x1b[38;2;215;95;95mRESOURCE_UNAVAIL\x1b[0m";
    }
    if (cat == ERR::CAT::ACCESS_DENIED) {
        return "\x1b[38;2;215;95;95mACCESS_DENIED\x1b[0m";
    }
    if (cat == ERR::CAT::WORK_PRECLUDED) {
        return "\x1b[38;2;215;95;95mWORK_PRECLUDED\x1b[0m";
    }
    if (cat == ERR::CAT::INPUT_TOO_LARGE) {
        return "\x1b[38;2;215;95;95mINPUT_TOO_LARGE\x1b[0m";
    }
    if (cat == ERR::CAT::HOST_OP_FAILED) {
        return "\x1b[38;2;215;95;95mHOST_OP_FAILED\x1b[0m";
    }
    if (cat == ERR::CAT::INPUT_TRUNCATED) {
        return "\x1b[38;2;215;95;95mINPUT_TRUNCATED\x1b[0m";
    }
    if (cat == ERR::CAT::REFERENCE_UNRESOLVED) {
        return "\x1b[38;2;215;95;95mREFERENCE_UNRESOLVED\x1b[0m";
    }
    if (cat == ERR::CAT::INPUT_REJECTED) {
        return "\x1b[38;2;215;95;95mINPUT_REJECTED\x1b[0m";
    }
    if (cat == ERR::CAT::CAPACITY_REACHED) {
        return "\x1b[38;2;215;95;95mCAPACITY_REACHED\x1b[0m";
    }
    if (cat == ERR::CAT::UNKNOWN_ID) {
        return "\x1b[38;2;215;95;95mUNKNOWN_ID\x1b[0m";
    }
    if (cat == ERR::CAT::BUFFER_TOO_SMALL) {
        return "\x1b[38;2;215;95;95mBUFFER_TOO_SMALL\x1b[0m";
    }
    if (cat == ERR::CAT::VERSION_MISMATCH) {
        return "\x1b[38;2;215;95;95mVERSION_MISMATCH\x1b[0m";
    }
    if (cat == ERR::CAT::VALUE_OUT_OF_RANGE) {
        return "\x1b[38;2;215;95;95mVALUE_OUT_OF_RANGE\x1b[0m";
    }
    if (cat == ERR::CAT::VALUE_NEGATIVE) {
        return "\x1b[38;2;215;95;95mVALUE_NEGATIVE\x1b[0m";
    }
    if (cat == ERR::CAT::VALUE_INVALID) {
        return "\x1b[38;2;215;95;95mVALUE_INVALID\x1b[0m";
    }

    return "\x1b[38;2;215;95;95mUNKNOWN_CATEGORY\x1b[0m";
}

const char* get_cat_help(uint32_t cat) {
    if (cat == ERR::CAT::UNKNOWN) {
        return "";
    }
    if (cat == ERR::CAT::HUB_NOT_FOUND) {
        return
            "Check that the IniSystem created the hub entity in on_start(), that spawn created the hub values "
                "for the entity, that the owner ID is the right one and that the value_id carries no typo";
    }
    if (cat == ERR::CAT::HUB_GLOBAL_MISSING) {
        return
            "Check that the source module's IniSystem created the GLOBAL hub value, that the source module is "
                "loaded and that the value_id carries no typo";
    }
    if (cat == ERR::CAT::COMPONENT_MISSING) {
        return
            "Check that the entity was spawned with its required components and that no other system removed "
                "the component";
    }
    if (cat == ERR::CAT::MANAGER_ABSENT) {
        return
            "Check that some system creates the manager entity and gives it its tag, and that the schedule "
                "places that creation before this system. An empty view means no entity carries the tag at all, "
                "so there is nothing to look inside";
    }
    if (cat == ERR::CAT::INVALID_ENTITY) {
        return
            "Check that the entity was not destroyed, that the stored entity ID is the right one and that no "
                "dangling reference survived";
    }
    if (cat == ERR::CAT::SCHEDULE_ORDER) {
        return
            "Check that the producer system is scheduled earlier and that the module definition carries the "
                ".run_after() constraint";
    }
    if (cat == ERR::CAT::CONFIG_MISSING) {
        return
            "Check that the variable is set in the unit's .env, that the .env is loaded before the plugin "
                "starts, that the variable name carries no typo and that the value is not empty";
    }
    if (cat == ERR::CAT::RESOURCE_UNAVAIL) {
        return
            "Check that the resource exists, is reachable AND not empty, because a file of zero length passes "
                "every existence test and still yields nothing. Then check the permissions on path or port, that "
                "the capacity of arena, buffer or descriptors is not exhausted, that the previous holder released "
                "it and that the read completed, since a short read leaves the resource present and unusable";
    }
    if (cat == ERR::CAT::ACCESS_DENIED) {
        return
            "Check that the caller identity was resolved before the check and that the required clearance or "
                "permission is recorded for that identity. The decision belongs in the error stream, not as a "
                "warning";
    }
    if (cat == ERR::CAT::WORK_PRECLUDED) {
        return
            "State noted. Nothing is missing, unreachable or unset and the work does not apply here";
    }
    if (cat == ERR::CAT::INPUT_TOO_LARGE) {
        return
            "Check the caller's payload against the documented cap and the cap itself against its intended "
                "value. Nothing was stored or forwarded because the whole input was rejected";
    }
    if (cat == ERR::CAT::HOST_OP_FAILED) {
        return
            "Check that the named path, handle or program is the intended one, then permissions and free "
                "space, then the OS error text in detail. That text names the cause while the category only names "
                "the class. On a REMOTE host the same checks apply to the far side, the reply carries the error "
                "text and local permissions and disk are the wrong trail";
    }
    if (cat == ERR::CAT::INPUT_TRUNCATED) {
        return
            "Check the declared length against what actually arrived and whether the sender split the "
                "message. Nothing was decoded because a short frame yields no partial result";
    }
    if (cat == ERR::CAT::REFERENCE_UNRESOLVED) {
        return
            "Check the PRODUCER of the reference, not this caller. Ask whether the target was ever created, "
                "whether a later step removed it and whether the reference stems from an older structure version";
    }
    if (cat == ERR::CAT::INPUT_REJECTED) {
        return
            "Check what the caller sent against what the contract allows and whether the rejection is the "
                "intended answer. Nothing was processed and this is not an engine fault";
    }
    if (cat == ERR::CAT::CAPACITY_REACHED) {
        return
            "Check the capacity itself first, because a container that is always full is sized wrong, not "
                "busy. Then check the producer rate against the drain rate, and what was refused and whether it "
                "can be retried";
    }
    if (cat == ERR::CAT::UNKNOWN_ID) {
        return
            "Check the spelling of the identifier against the registry that owns it, whether the producer "
                "registered it before this call and whether the registry itself is the one you expect";
    }
    if (cat == ERR::CAT::BUFFER_TOO_SMALL) {
        return
            "Check the buffer size at the CALLER, which owns the buffer rather than this function, against "
                "the maximum this operation can produce. Nothing was written because a short buffer yields no "
                "partial result";
    }
    if (cat == ERR::CAT::VERSION_MISMATCH) {
        return
            "Check expected against received, and both belong in the line. Then check which side is older and "
                "whether the two were built from the same tree";
    }
    if (cat == ERR::CAT::VALUE_OUT_OF_RANGE) {
        return
            "Check the value against the range that rejected it and decide which side is wrong, the value or "
                "the range. Nothing was applied and the operation ends here";
    }
    if (cat == ERR::CAT::VALUE_NEGATIVE) {
        return
            "Check the producer of the value, because a negative here is not correctable at this end, and "
                "whether a subtraction underflowed. Nothing was applied and the operation ends here";
    }
    if (cat == ERR::CAT::VALUE_INVALID) {
        return
            "Check what the value means in the contract that rejected it and the producer that wrote it. "
                "Nothing was applied and the operation ends here";
    }

    return
        "The value passed is not a category in core/ase-log/data/log_categories.json. Check the constant "
            "at the call site: a category is ERR::CAT::<NAME> or WRN::CAT::<NAME>, and its value is the hash "
            "of that NAME - a hand-written number cannot be one.";
}

const char* get_cat_short(uint32_t cat) {
    if (cat == ERR::CAT::UNKNOWN) {
        return "";
    }
    if (cat == ERR::CAT::HUB_NOT_FOUND) {
        return "chk owner ID and val_id";
    }
    if (cat == ERR::CAT::HUB_GLOBAL_MISSING) {
        return "chk src mod and val_id";
    }
    if (cat == ERR::CAT::COMPONENT_MISSING) {
        return "reqd comp not on enty";
    }
    if (cat == ERR::CAT::MANAGER_ABSENT) {
        return "mgr enty was never crtd";
    }
    if (cat == ERR::CAT::INVALID_ENTITY) {
        return "enty dstd or ID stale";
    }
    if (cat == ERR::CAT::SCHEDULE_ORDER) {
        return "prod sys runs too late";
    }
    if (cat == ERR::CAT::CONFIG_MISSING) {
        return "set var in unit's .env";
    }
    if (cat == ERR::CAT::RESOURCE_UNAVAIL) {
        return "named but not obtainable";
    }
    if (cat == ERR::CAT::ACCESS_DENIED) {
        return "idnt lacks clrn";
    }
    if (cat == ERR::CAT::WORK_PRECLUDED) {
        return "state precludes work";
    }
    if (cat == ERR::CAT::INPUT_TOO_LARGE) {
        return "pyld over documented cap";
    }
    if (cat == ERR::CAT::HOST_OP_FAILED) {
        return "OS err text names cause";
    }
    if (cat == ERR::CAT::INPUT_TRUNCATED) {
        return "inp ended bfr declared end";
    }
    if (cat == ERR::CAT::REFERENCE_UNRESOLVED) {
        return "chk prod of ref";
    }
    if (cat == ERR::CAT::INPUT_REJECTED) {
        return "caller sent something unserviceable";
    }
    if (cat == ERR::CAT::CAPACITY_REACHED) {
        return "full, chk size and drn rate";
    }
    if (cat == ERR::CAT::UNKNOWN_ID) {
        return "idnt stands in no reg";
    }
    if (cat == ERR::CAT::BUFFER_TOO_SMALL) {
        return "caller buf too small";
    }
    if (cat == ERR::CAT::VERSION_MISMATCH) {
        return "expc and received dfrs";
    }
    if (cat == ERR::CAT::VALUE_OUT_OF_RANGE) {
        return "val left vld rng";
    }
    if (cat == ERR::CAT::VALUE_NEGATIVE) {
        return "chk for subtraction udfl";
    }
    if (cat == ERR::CAT::VALUE_INVALID) {
        return "val breaks cntr";
    }

    return "cat val not in SSOT";
}

const char* get_cat_tail(uint32_t cat) {
    if (cat == ERR::CAT::UNKNOWN) {
        return "";
    }
    if (cat == ERR::CAT::HUB_NOT_FOUND) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk IniSystem crtd hub enty in on_start(), spawn crtd hub values for enty, owner ID is right one "
                "and val_id carries no typo"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::HUB_GLOBAL_MISSING) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk src mod's IniSystem crtd glob hub val, src mod is lded and val_id carries no typo"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::COMPONENT_MISSING) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk enty was spawned with reqd components and no other sys rmvd comp"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::MANAGER_ABSENT) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk some sys creates mgr enty and gives it tag, and schd places creation bfr sys. empty view mns "
                "no enty carries tag at all, so there is nothing to look insd"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::INVALID_ENTITY) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk enty was not dstd, strd enty ID is right one and no dang ref survived"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::SCHEDULE_ORDER) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk prod sys is schd earlier and mod defn carries .run_after() cstr"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::CONFIG_MISSING) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk var is set in unit's .env, .env is lded bfr plgn starts, var name carries no typo and val is "
                "not empty"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::RESOURCE_UNAVAIL) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk rsrc exists, is reachable AND not empty, because file of zero len passes every exst test and "
                "still yields nothing. Then chk permissions on path or port, cap of arena, buf or descriptors is "
                "not exht, prev hldr rlsd it and read cmpl, since short read leaves rsrc pres and unusable"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::ACCESS_DENIED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk caller idnt was resolved bfr chk and reqd clrn or perm is recorded for idnt. dcsn belongs in "
                "err strm, not as warn"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::WORK_PRECLUDED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "State noted. Nothing is miss, unrc or unset and work does not apply here"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::INPUT_TOO_LARGE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk caller's pyld against documented cap and cap itself against intended val. Nothing was strd "
                "or forwarded because whole inp was rjct"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::HOST_OP_FAILED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk named path, hndl or program is intended one, then permissions and free space, then OS err "
                "text in detl. text names cause while cat only names cls. On REMOTE host same checks apply to far "
                "side, reply carries err text and local permissions and disk are wrong trl"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::INPUT_TRUNCATED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk declared len against what actually arvd and whether sndr split msg. Nothing was decd because "
                "short frame yields no prtl rslt"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::REFERENCE_UNRESOLVED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk prod of ref, not caller. Ask whether tgt was ever crtd, whether later step rmvd it and "
                "whether ref stems from older strc ver"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::INPUT_REJECTED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk what caller sent against what cntr allows and whether rjct is intended answer. Nothing was "
                "processed and is not engn fault"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::CAPACITY_REACHED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk cap itself fst, because container is always full is sized wrong, not busy. Then chk prod "
                "rate against drn rate, and what was refused and whether it can be retried"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::UNKNOWN_ID) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk spelling of idnt against reg owns it, whether prod registered it bfr call and whether reg "
                "itself is one you expect"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::BUFFER_TOO_SMALL) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk buf size at CALLER, which owns buf rather than func, against maxm operation can produce. "
                "Nothing was written because short buf yields no prtl rslt"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::VERSION_MISMATCH) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk expc against received, and both blng in line. Then chk which side is older and whether two "
                "were blt from same tree"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::VALUE_OUT_OF_RANGE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk val against rng rjct it and dcde which side is wrong, val or rng. Nothing was applied and "
                "operation ends here"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::VALUE_NEGATIVE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk prod of val, because negv here is not correctable at end, and whether subtraction "
                "underflowed. Nothing was applied and operation ends here"
            "\x1b[0m\n";
    }
    if (cat == ERR::CAT::VALUE_INVALID) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk what val mns in cntr rjct it and prod wrote it. Nothing was applied and operation ends here"
            "\x1b[0m\n";
    }

    return
        "\n\x1b[38;2;108;108;108m    "
        "val passed is not cat in core/ase-log/data/log_categories.json. chk constant at call site: cat "
            "is ERR::CAT::<NAME> or WRN::CAT::<NAME>, and val is hash of NAME - hand-written num cant be one."
        "\x1b[0m\n";
}

const char* get_cat_suffix(uint32_t cat) {
    if (cat == ERR::CAT::UNKNOWN) {
        return "";
    }
    if (cat == ERR::CAT::HUB_NOT_FOUND) {
        return "";
    }
    if (cat == ERR::CAT::HUB_GLOBAL_MISSING) {
        return " (GLOBAL)";
    }
    if (cat == ERR::CAT::COMPONENT_MISSING) {
        return "";
    }
    if (cat == ERR::CAT::MANAGER_ABSENT) {
        return "";
    }
    if (cat == ERR::CAT::INVALID_ENTITY) {
        return "";
    }
    if (cat == ERR::CAT::SCHEDULE_ORDER) {
        return "";
    }
    if (cat == ERR::CAT::CONFIG_MISSING) {
        return "";
    }
    if (cat == ERR::CAT::RESOURCE_UNAVAIL) {
        return "";
    }
    if (cat == ERR::CAT::ACCESS_DENIED) {
        return "";
    }
    if (cat == ERR::CAT::WORK_PRECLUDED) {
        return "";
    }
    if (cat == ERR::CAT::INPUT_TOO_LARGE) {
        return "";
    }
    if (cat == ERR::CAT::HOST_OP_FAILED) {
        return "";
    }
    if (cat == ERR::CAT::INPUT_TRUNCATED) {
        return "";
    }
    if (cat == ERR::CAT::REFERENCE_UNRESOLVED) {
        return "";
    }
    if (cat == ERR::CAT::INPUT_REJECTED) {
        return "";
    }
    if (cat == ERR::CAT::CAPACITY_REACHED) {
        return "";
    }
    if (cat == ERR::CAT::UNKNOWN_ID) {
        return "";
    }
    if (cat == ERR::CAT::BUFFER_TOO_SMALL) {
        return "";
    }
    if (cat == ERR::CAT::VERSION_MISMATCH) {
        return "";
    }
    if (cat == ERR::CAT::VALUE_OUT_OF_RANGE) {
        return "";
    }
    if (cat == ERR::CAT::VALUE_NEGATIVE) {
        return "";
    }
    if (cat == ERR::CAT::VALUE_INVALID) {
        return "";
    }

    // Kein Suffix - siehe Generatorkommentar: die Marke steht im NAMEN.
    return "";
}

const char* get_wrn_cat_name(uint32_t cat) {
    if (cat == WRN::CAT::UNKNOWN) {
        return "\x1b[38;2;215;95;95mUNKNOWN\x1b[0m";
    }
    if (cat == WRN::CAT::VALUE_OUT_OF_RANGE) {
        return "\x1b[38;2;215;95;95mVALUE_OUT_OF_RANGE\x1b[0m";
    }
    if (cat == WRN::CAT::VALUE_NEGATIVE) {
        return "\x1b[38;2;215;95;95mVALUE_NEGATIVE\x1b[0m";
    }
    if (cat == WRN::CAT::VALUE_INVALID) {
        return "\x1b[38;2;215;95;95mVALUE_INVALID\x1b[0m";
    }
    if (cat == WRN::CAT::INPUT_REJECTED) {
        return "\x1b[38;2;215;95;95mINPUT_REJECTED\x1b[0m";
    }
    if (cat == WRN::CAT::CAPACITY_REACHED) {
        return "\x1b[38;2;215;95;95mCAPACITY_REACHED\x1b[0m";
    }
    if (cat == WRN::CAT::WORK_PRECLUDED) {
        return "\x1b[38;2;215;95;95mWORK_PRECLUDED\x1b[0m";
    }
    if (cat == WRN::CAT::REFERENCE_UNRESOLVED) {
        return "\x1b[38;2;215;95;95mREFERENCE_UNRESOLVED\x1b[0m";
    }
    if (cat == WRN::CAT::HOST_OP_FAILED) {
        return "\x1b[38;2;215;95;95mHOST_OP_FAILED\x1b[0m";
    }
    if (cat == WRN::CAT::INPUT_INCOMPLETE) {
        return "\x1b[38;2;215;95;95mINPUT_INCOMPLETE\x1b[0m";
    }
    if (cat == WRN::CAT::RESOURCE_UNAVAIL) {
        return "\x1b[38;2;215;95;95mRESOURCE_UNAVAIL\x1b[0m";
    }
    if (cat == WRN::CAT::BUFFER_TOO_SMALL) {
        return "\x1b[38;2;215;95;95mBUFFER_TOO_SMALL\x1b[0m";
    }
    if (cat == WRN::CAT::OVERRIDE_ACTIVE) {
        return "\x1b[38;2;215;95;95mOVERRIDE_ACTIVE\x1b[0m";
    }
    if (cat == WRN::CAT::HUB_NOT_FOUND) {
        return "\x1b[38;2;215;95;95mHUB_NOT_FOUND\x1b[0m";
    }
    if (cat == WRN::CAT::HUB_GLOBAL_MISSING) {
        return "\x1b[38;2;215;95;95mHUB_GLOBAL_MISSING\x1b[0m";
    }
    if (cat == WRN::CAT::COMPONENT_MISSING) {
        return "\x1b[38;2;215;95;95mCOMPONENT_MISSING\x1b[0m";
    }
    if (cat == WRN::CAT::MANAGER_ABSENT) {
        return "\x1b[38;2;215;95;95mMANAGER_ABSENT\x1b[0m";
    }
    if (cat == WRN::CAT::INVALID_ENTITY) {
        return "\x1b[38;2;215;95;95mINVALID_ENTITY\x1b[0m";
    }
    if (cat == WRN::CAT::SCHEDULE_ORDER) {
        return "\x1b[38;2;215;95;95mSCHEDULE_ORDER\x1b[0m";
    }
    if (cat == WRN::CAT::CONFIG_MISSING) {
        return "\x1b[38;2;215;95;95mCONFIG_MISSING\x1b[0m";
    }
    if (cat == WRN::CAT::INPUT_TOO_LARGE) {
        return "\x1b[38;2;215;95;95mINPUT_TOO_LARGE\x1b[0m";
    }
    if (cat == WRN::CAT::INPUT_TRUNCATED) {
        return "\x1b[38;2;215;95;95mINPUT_TRUNCATED\x1b[0m";
    }
    if (cat == WRN::CAT::UNKNOWN_ID) {
        return "\x1b[38;2;215;95;95mUNKNOWN_ID\x1b[0m";
    }
    if (cat == WRN::CAT::VERSION_MISMATCH) {
        return "\x1b[38;2;215;95;95mVERSION_MISMATCH\x1b[0m";
    }

    return "\x1b[38;2;215;95;95mUNKNOWN_CATEGORY\x1b[0m";
}

const char* get_wrn_cat_help(uint32_t cat) {
    if (cat == WRN::CAT::UNKNOWN) {
        return "";
    }
    if (cat == WRN::CAT::VALUE_OUT_OF_RANGE) {
        return
            "Check the value against the range it left. To clamp, reject or keep it is the caller's decision";
    }
    if (cat == WRN::CAT::VALUE_NEGATIVE) {
        return "Check why the value is negative. To zero, reject or keep it is the caller's decision";
    }
    if (cat == WRN::CAT::VALUE_INVALID) {
        return "Check why the value is semantically invalid. The caller decides how to proceed";
    }
    if (cat == WRN::CAT::INPUT_REJECTED) {
        return "The request was rejected and the caller must correct it. This is not an engine fault";
    }
    if (cat == WRN::CAT::CAPACITY_REACHED) {
        return
            "Check which entry was dropped and whether it can be recovered, then the producer rate against "
                "the drain rate, then the capacity itself, because a queue that is always full is sized wrong, "
                "not busy";
    }
    if (cat == WRN::CAT::WORK_PRECLUDED) {
        return
            "State noted. Nothing is missing, unreachable or unset and the work does not apply here";
    }
    if (cat == WRN::CAT::REFERENCE_UNRESOLVED) {
        return
            "Check the PRODUCER of the reference, not this caller. Ask whether the target was ever created at "
                "this level, whether a later step removed it and whether the reference stems from an older "
                "structure version";
    }
    if (cat == WRN::CAT::HOST_OP_FAILED) {
        return
            "Check that the named path, handle or program is the intended one, then permissions and free "
                "space, then the OS error text in detail. That text names the cause while the category only names "
                "the class. On a REMOTE host the same checks apply to the far side, the reply carries the error "
                "text and local permissions and disk are the wrong trail. The run continues with reduced "
                "capability";
    }
    if (cat == WRN::CAT::INPUT_INCOMPLETE) {
        return
            "Check whether the optional part was meant to be there, the producer that should have filled it "
                "and what the reduced result is missing. The work DID happen, just with less";
    }
    if (cat == WRN::CAT::RESOURCE_UNAVAIL) {
        return
            "Check that the resource exists, is reachable AND not empty, then the permissions on path or port "
                "and that the previous holder released it. The run continues either way";
    }
    if (cat == WRN::CAT::BUFFER_TOO_SMALL) {
        return
            "Check the buffer size at the CALLER, which owns the buffer rather than this function, against "
                "the maximum this operation can produce, and what was truncated or skipped";
    }
    if (cat == WRN::CAT::OVERRIDE_ACTIVE) {
        return
            "Check whether the override is meant to be active HERE, because a development switch reaching "
                "production is the case this line exists for. Then check who set it and what the default would "
                "have been. The run continues with the deviating value";
    }
    if (cat == WRN::CAT::HUB_NOT_FOUND) {
        return
            "Check that the IniSystem created the hub entity in on_start(), that spawn created the hub values "
                "for the entity, that the owner ID is the right one and that the value_id carries no typo. The "
                "run continues, usually with a default";
    }
    if (cat == WRN::CAT::HUB_GLOBAL_MISSING) {
        return
            "Check that the source module's IniSystem created the GLOBAL hub value, that the source module is "
                "loaded and that the value_id carries no typo. The run continues, usually with a default";
    }
    if (cat == WRN::CAT::COMPONENT_MISSING) {
        return
            "Check that the entity was spawned with its required components and that no other system removed "
                "the component. This entity is skipped and the rest of the view is processed";
    }
    if (cat == WRN::CAT::MANAGER_ABSENT) {
        return
            "Check that some system creates the manager entity and gives it its tag, and that the schedule "
                "places that creation before this system. An empty view means no entity carries the tag at all in "
                "this pass, so there is nothing to look inside";
    }
    if (cat == WRN::CAT::INVALID_ENTITY) {
        return
            "Check that the entity was not destroyed, that the stored entity ID is the right one and that no "
                "dangling reference survived. This entity is skipped and the run continues";
    }
    if (cat == WRN::CAT::SCHEDULE_ORDER) {
        return
            "Check that the producer system is scheduled earlier and that the module definition carries the "
                ".run_after() constraint. This tick used stale or missing data and the loop continues";
    }
    if (cat == WRN::CAT::CONFIG_MISSING) {
        return
            "Check that the variable is set in the unit's .env, that the .env is loaded before the plugin "
                "starts and that the variable name carries no typo. The run continues with the default value";
    }
    if (cat == WRN::CAT::INPUT_TOO_LARGE) {
        return
            "Check the caller's payload against the documented cap and the cap itself against its intended "
                "value, then what was kept and what was cut. The run continues with the reduced input";
    }
    if (cat == WRN::CAT::INPUT_TRUNCATED) {
        return
            "Check the declared length against what actually arrived and whether the sender split the "
                "message. This frame was dropped and the next one is processed";
    }
    if (cat == WRN::CAT::UNKNOWN_ID) {
        return
            "Check the spelling of the identifier against the registry that owns it and whether the producer "
                "registered it before this call. This entry is skipped and the run continues";
    }
    if (cat == WRN::CAT::VERSION_MISMATCH) {
        return
            "Check expected against received, and both belong in the line. Then check which side is older and "
                "what still works and what does not. The run continues with reduced capability";
    }

    return
        "The value passed is not a category in core/ase-log/data/log_categories.json. Check the constant "
            "at the call site: a category is ERR::CAT::<NAME> or WRN::CAT::<NAME>, and its value is the hash "
            "of that NAME - a hand-written number cannot be one.";
}

const char* get_wrn_cat_short(uint32_t cat) {
    if (cat == WRN::CAT::UNKNOWN) {
        return "";
    }
    if (cat == WRN::CAT::VALUE_OUT_OF_RANGE) {
        return "val left vld rng";
    }
    if (cat == WRN::CAT::VALUE_NEGATIVE) {
        return "chk for subtraction udfl";
    }
    if (cat == WRN::CAT::VALUE_INVALID) {
        return "val breaks cntr";
    }
    if (cat == WRN::CAT::INPUT_REJECTED) {
        return "caller sent something unserviceable";
    }
    if (cat == WRN::CAT::CAPACITY_REACHED) {
        return "full, chk size and drn rate";
    }
    if (cat == WRN::CAT::WORK_PRECLUDED) {
        return "state precludes work";
    }
    if (cat == WRN::CAT::REFERENCE_UNRESOLVED) {
        return "chk prod of ref";
    }
    if (cat == WRN::CAT::HOST_OP_FAILED) {
        return "OS err text names cause";
    }
    if (cat == WRN::CAT::INPUT_INCOMPLETE) {
        return "optl part miss, work rdcd";
    }
    if (cat == WRN::CAT::RESOURCE_UNAVAIL) {
        return "named but not obtainable";
    }
    if (cat == WRN::CAT::BUFFER_TOO_SMALL) {
        return "caller buf too small";
    }
    if (cat == WRN::CAT::OVERRIDE_ACTIVE) {
        return "ovrd deviates from dflt";
    }
    if (cat == WRN::CAT::HUB_NOT_FOUND) {
        return "chk owner ID and val_id";
    }
    if (cat == WRN::CAT::HUB_GLOBAL_MISSING) {
        return "chk src mod and val_id";
    }
    if (cat == WRN::CAT::COMPONENT_MISSING) {
        return "reqd comp not on enty";
    }
    if (cat == WRN::CAT::MANAGER_ABSENT) {
        return "mgr enty was never crtd";
    }
    if (cat == WRN::CAT::INVALID_ENTITY) {
        return "enty dstd or ID stale";
    }
    if (cat == WRN::CAT::SCHEDULE_ORDER) {
        return "prod sys runs too late";
    }
    if (cat == WRN::CAT::CONFIG_MISSING) {
        return "set var in unit's .env";
    }
    if (cat == WRN::CAT::INPUT_TOO_LARGE) {
        return "pyld over documented cap";
    }
    if (cat == WRN::CAT::INPUT_TRUNCATED) {
        return "inp ended bfr declared end";
    }
    if (cat == WRN::CAT::UNKNOWN_ID) {
        return "idnt stands in no reg";
    }
    if (cat == WRN::CAT::VERSION_MISMATCH) {
        return "expc and received dfrs";
    }

    return "cat val not in SSOT";
}

const char* get_wrn_cat_tail(uint32_t cat) {
    if (cat == WRN::CAT::UNKNOWN) {
        return "";
    }
    if (cat == WRN::CAT::VALUE_OUT_OF_RANGE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk val against rng it left. To clamp, rjct or keep it is caller's dcsn"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::VALUE_NEGATIVE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk why val is negv. To zero, rjct or keep it is caller's dcsn"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::VALUE_INVALID) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk why val is semantically invl. caller decides how to prcd"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::INPUT_REJECTED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "req was rjct and caller must crct it. is not engn fault"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::CAPACITY_REACHED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk which entry was dropped and whether it can be recovered, then prod rate against drn rate, "
                "then cap itself, because que is always full is sized wrong, not busy"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::WORK_PRECLUDED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "State noted. Nothing is miss, unrc or unset and work does not apply here"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::REFERENCE_UNRESOLVED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk prod of ref, not caller. Ask whether tgt was ever crtd at lvl, whether later step rmvd it "
                "and whether ref stems from older strc ver"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::HOST_OP_FAILED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk named path, hndl or program is intended one, then permissions and free space, then OS err "
                "text in detl. text names cause while cat only names cls. On REMOTE host same checks apply to far "
                "side, reply carries err text and local permissions and disk are wrong trl. run continues with "
                "rdcd capb"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::INPUT_INCOMPLETE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk whether optl part was meant to be there, prod should have filled it and what rdcd rslt is "
                "miss. work DID happen, just with less"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::RESOURCE_UNAVAIL) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk rsrc exists, is reachable AND not empty, then permissions on path or port and prev hldr rlsd "
                "it. run continues either way"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::BUFFER_TOO_SMALL) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk buf size at CALLER, which owns buf rather than func, against maxm operation can produce, and "
                "what was truncated or skipped"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::OVERRIDE_ACTIVE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk whether ovrd is meant to be actv HERE, because dev swtc reaching prod is case line exists "
                "for. Then chk who set it and what dflt would have been. run continues with deviating val"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::HUB_NOT_FOUND) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk IniSystem crtd hub enty in on_start(), spawn crtd hub values for enty, owner ID is right one "
                "and val_id carries no typo. run continues, usually with dflt"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::HUB_GLOBAL_MISSING) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk src mod's IniSystem crtd glob hub val, src mod is lded and val_id carries no typo. run "
                "continues, usually with dflt"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::COMPONENT_MISSING) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk enty was spawned with reqd components and no other sys rmvd comp. enty is skipped and rest "
                "of view is processed"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::MANAGER_ABSENT) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk some sys creates mgr enty and gives it tag, and schd places creation bfr sys. empty view mns "
                "no enty carries tag at all in pass, so there is nothing to look insd"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::INVALID_ENTITY) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk enty was not dstd, strd enty ID is right one and no dang ref survived. enty is skipped and "
                "run continues"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::SCHEDULE_ORDER) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk prod sys is schd earlier and mod defn carries .run_after() cstr. tick used stale or miss "
                "data and loop continues"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::CONFIG_MISSING) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk var is set in unit's .env, .env is lded bfr plgn starts and var name carries no typo. run "
                "continues with dflt val"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::INPUT_TOO_LARGE) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk caller's pyld against documented cap and cap itself against intended val, then what was kept "
                "and what was cut. run continues with rdcd inp"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::INPUT_TRUNCATED) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk declared len against what actually arvd and whether sndr split msg. frame was dropped and "
                "next one is processed"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::UNKNOWN_ID) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk spelling of idnt against reg owns it and whether prod registered it bfr call. entry is "
                "skipped and run continues"
            "\x1b[0m\n";
    }
    if (cat == WRN::CAT::VERSION_MISMATCH) {
        return
            "\n\x1b[38;2;108;108;108m    "
            "chk expc against received, and both blng in line. Then chk which side is older and what still "
                "works and what does not. run continues with rdcd capb"
            "\x1b[0m\n";
    }

    return
        "\n\x1b[38;2;108;108;108m    "
        "val passed is not cat in core/ase-log/data/log_categories.json. chk constant at call site: cat "
            "is ERR::CAT::<NAME> or WRN::CAT::<NAME>, and val is hash of NAME - hand-written num cant be one."
        "\x1b[0m\n";
}

}  // namespace ase::log::detail
