#pragma once

/**
 * ASE CORE INFRASTRUCTURE HEADER
 *
 * AUTO-GENERATED FILE - DO NOT EDIT!
 * Edit core/ase-log/data/log_categories.json and run
 * core/ase-log/scripts/gen_log_cat.py instead. A hand fix here survives
 * exactly until the next generator run.
 *
 * @file        log_err_cat_gen.hpp
 * @design      DSGN_021
 * @brief       ERR::CAT and WRN::CAT name hashes plus the lookup declarations
 * @description Constants only - each one is the FNV-1a hash of its own NAME.
 *              There is no id, no table and no counter: a category cannot be
 *              renumbered, so inserting or reordering one changes nothing that
 *              already exists. The name/help/suffix lookups live in
 *              log_err_cat_gen.cpp, so adding a category recompiles ONE file
 *              instead of the tree.
 *
 * @module      ase-log
 * @layer       1 (Core)
 * @category    ecs/module
 * @created     2026-08-23
 * @modified    2026-08-23
 * @version     1.0.0
 *
 * CORE INFRASTRUCTURE COMPLIANCE
 *
 * [ ] NOT an ECS Component or System
 * [ ] Layer dependencies correct (L0: no ASE deps, L1: L0 only)
 * [ ] No global mutable state (constexpr/const only)
 * [ ] No singletons or static mutable variables
 * [ ] Thread-safe by design (pure functions or explicit mutex)
 * [ ] All public functions documented with @brief, @param, @return
 * [ ] constexpr where possible (compile-time evaluation)
 * [ ] noexcept where possible (no-throw guarantee)
 * [ ] [[nodiscard]] on functions returning values
 * [ ] No magic numbers (use named constants)
 * [ ] No implicit conversions (use explicit constructors)
 * [ ] Header-only OR header+cpp pattern (not mixed)
 * [ ] Include guards via #pragma once
 * [ ] Namespace matches module: ase::{module}
 * [ ] No circular dependencies
 * [ ] No macros (except include guards) - use constexpr/templates
 * [ ] API stable (changes require version bump)
 *
 * Generated by: core/ase-log/scripts/gen_log_cat.py
 * Source: core/ase-log/data/log_categories.json
 */

#include <cstdint>

namespace ase::log {

namespace ERR {
namespace CAT {
    // Die ausdrueckliche Nicht-Aussage: der Aufrufer weiss, dass er nichts einzuordnen hat.
    // NICHT der Rueckfall - ein unbekannter Hash landet seit dem Hash-Umbau in einer lauten
    // Marke, nicht hier.
    // FNV-1a of "ERR_UNKNOWN" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t UNKNOWN = 3993994373u;
    // Hub entity doesn't exist for owner+value_id
    // FNV-1a of "ERR_HUB_NOT_FOUND" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t HUB_NOT_FOUND = 3531489801u;
    // GLOBAL hub value missing. Die EINZIGE Kategorie mit Zusatz - er stand frueher fest im
    // Formatstring der Drei-Argument-Ueberladung und gehoerte damit der STELLIGKEIT statt der
    // KATEGORIE.
    // FNV-1a of "ERR_HUB_GLOBAL_MISSING" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t HUB_GLOBAL_MISSING = 76183065u;
    // Required component not on entity
    // FNV-1a of "ERR_COMPONENT_MISSING" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t COMPONENT_MISSING = 2810980563u;
    // Der VERWALTER eines Moduls existiert nicht: die Sicht auf seinen Manager-Tag ist LEER,
    // es gibt keine Entity zu nennen. Nicht COMPONENT_MISSING - das setzt eine VORHANDENE
    // Entity voraus, der ein Component fehlt, und behauptet hier zweimal etwas Falsches, weil
    // es weder eine Entity noch ein Component gibt. Nicht INVALID_ENTITY (nichts ist
    // zerstoert, es wurde nie etwas angelegt), nicht REFERENCE_UNRESOLVED (es gibt keinen
    // Verweis, es wird eine Sicht gebildet), nicht RESOURCE_UNAVAIL (das meint ausdruecklich
    // eine Ressource AUSSERHALB der Registry, und eine Sicht IST die Registry), nicht
    // HUB_NOT_FOUND (nicht der Hub, sondern der Manager-Tag eines Moduls). Die Bauform ist
    // baumweit dieselbe: view<XxxMgrTag>() gefolgt von einer empty()- oder front()-Pruefung.
    // ERR-Entsprechung von WRN::CAT::MANAGER_ABSENT: dieselbe Sache, aber der Vorgang endet
    // hier statt weiterzulaufen.
    // FNV-1a of "ERR_MANAGER_ABSENT" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t MANAGER_ABSENT = 2050836936u;
    // Entity ID is invalid or destroyed
    // FNV-1a of "ERR_INVALID_ENTITY" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INVALID_ENTITY = 2910219150u;
    // System runs before its dependency
    // FNV-1a of "ERR_SCHEDULE_ORDER" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t SCHEDULE_ORDER = 1241647959u;
    // Env/config value absent - lives BEFORE the registry. Kein GLOBAL-Zusatz: es liegt vor
    // der Registry.
    // FNV-1a of "ERR_CONFIG_MISSING" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t CONFIG_MISSING = 402514332u;
    // Eine RESSOURCE ausserhalb der Registry steht nicht zur Verfuegung: Datei, Socket, Arena,
    // Puffer, Uhr. Nicht COMPONENT_MISSING (Entity-Aussage) und nicht CONFIG_MISSING (nicht
    // gesetzter Wert) - hier IST etwas konfiguriert und benannt, es laesst sich nur nicht
    // belegen. HIERHER GEHOERT DIE FEHLGESCHLAGENE SLOT-VERGABE EINES VERWALTERS OHNE
    // OBERGRENZE, und das ist die Gegenrichtung der Bedingung unter CAPACITY_REACHED: der
    // Ungueltig-Wert der Kennung sagt 'nicht zu haben', nie 'voll'. ZUERST DER GEGENFALL,
    // damit niemand pauschal hierher umschreibt: fuehrt der aufgerufene Verwalter einen ECHTEN
    // Deckel - ein festes Array, ein Kapazitaetsfeld, eine full()-Abfrage -, dann gilt
    // CAPACITY_REACHED und NICHT diese Kategorie; ReplicaSklPrivResourceManager und das feste
    // Staging-Array in ReplicaCapNodeRowSystem sind die belegten Beispiele dafuer. Erst wo die
    // Vergabe KEINEN Fehlerpfad traegt - gemessen an ReplicationPstResourceManager und
    // ReplicationLodResourceManager -, ist diese Kategorie die richtige. Die Pruefung ist in
    // beiden Richtungen dieselbe und steht ausgeschrieben unter CAPACITY_REACHED.
    // FNV-1a of "ERR_RESOURCE_UNAVAIL" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t RESOURCE_UNAVAIL = 3319675844u;
    // Ein AUTORISIERUNGSENTSCHEID auf Fehlerebene: der Aufrufer ist bekannt, die Anfrage
    // wohlgeformt, und sie wird abgelehnt. Bewusst NICHT WRN::CAT::INPUT_REJECTED - eine
    // Warnung faellt aus jedem ERR-Filter heraus.
    // FNV-1a of "ERR_ACCESS_DENIED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t ACCESS_DENIED = 304657963u;
    // Der ZUSTAND erlaubt die Arbeit nicht - und nichts ist kaputt, unerreichbar oder
    // ungesetzt. Der Hilfetext sagt bewusst NICHTS ueber den Kontrollfluss: dieser Zustand ist
    // oft der gewollte. BEDINGUNG, und sie faellt genau dort, wo die Kategorie am haeufigsten
    // falsch gewaehlt wird: der Hilfetext schliesst 'unerreichbar' AUSDRUECKLICH aus, und eine
    // fehlgeschlagene Slot-Vergabe IST unerreichbar - dort faellt die Kategorie aus und
    // RESOURCE_UNAVAIL gilt. Wer WORK_PRECLUDED nach einer Vergabe setzt, hat den eigenen
    // Hilfetext gegen sich. Die ausgeschriebene Pruefung steht unter CAPACITY_REACHED und gilt
    // hier gleichermassen.
    // FNV-1a of "ERR_WORK_PRECLUDED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t WORK_PRECLUDED = 2310557349u;
    // Eine EINGABE ueberschreitet eine feste Obergrenze und wird als Ganzes verworfen. Nicht
    // RESOURCE_UNAVAIL (dort ist die Aufnahme erschoepft, hier war sie nie zustaendig) und
    // nicht WRN::CAT::INPUT_REJECTED - der Vorgang endet, statt weiterzulaufen.
    // FNV-1a of "ERR_INPUT_TOO_LARGE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_TOO_LARGE = 570146786u;
    // Ein VORGANG am Wirtssystem ist gescheitert: anlegen, schreiben, ersetzen, ein fremdes
    // Programm starten. DERSELBE VORGANG AUF EINEM FREMDEN WIRTSSYSTEM gehoert ebenfalls
    // hierher: eine Einheit, die den Schritt fuer uns ausgefuehrt hat, meldet seinen
    // Fehlschlag zurueck. Der Rundlauf selbst ist dabei GELUNGEN - die Gegenseite war
    // erreichbar und hat geantwortet; gescheitert ist, was an ihrem Ende lief. Deshalb nicht
    // RESOURCE_UNAVAIL: dort kommt keine Antwort. Abgrenzung: CONFIG_MISSING heisst, es wurde
    // nie etwas versucht; RESOURCE_UNAVAIL heisst, die Ressource existiert und ist
    // unerreichbar. Hier war alles gesetzt, der Vorgang selbst ist fehlgeschlagen. Auf
    // WRN-Ebene gibt es dieselbe Kategorie fuer den Fall, dass der Durchlauf danach
    // weitergeht.
    // FNV-1a of "ERR_HOST_OP_FAILED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t HOST_OP_FAILED = 1727753321u;
    // Eine EINGABE endet vor ihrem angekuendigten Ende: ein Rahmen ist zu kurz, ein Feld fehlt
    // hinten. Die Spiegelhaelfte von INPUT_TOO_LARGE - dort ueberschreitet die Eingabe eine
    // Obergrenze, hier erreicht sie ihre Untergrenze nicht. Nicht VALUE_INVALID: der Wert ist
    // nicht falsch, er ist unvollstaendig, und es gibt keinen Teilerfolg.
    // FNV-1a of "ERR_INPUT_TRUNCATED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_TRUNCATED = 3212576698u;
    // Der VERWEIS ist wohlgeformt, das Ziel existiert nicht. ERR-Entsprechung von
    // WRN::CAT::REFERENCE_UNRESOLVED: dieselbe Sache, aber der Vorgang endet hier statt
    // weiterzulaufen. Wie dort ist es eine NACHGELAGERTE Beobachtung - der Hilfetext schickt
    // den Leser zum ERZEUGER der Adresse, nicht zum Aufrufer.
    // FNV-1a of "ERR_REFERENCE_UNRESOLVED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t REFERENCE_UNRESOLVED = 1196209060u;
    // Ein fremder Aufrufer hat etwas Unbedienbares geschickt, und der Vorgang ENDET.
    // ERR-Entsprechung von WRN::CAT::INPUT_REJECTED: dieselbe Sache, anderer Ernstfall - dort
    // laeuft der Durchlauf weiter, hier nicht. Wer Ablehnungen im Fehlerstrom auswerten will,
    // findet sie nur hier; eine Warnung faellt aus jedem ERR-Filter.
    // FNV-1a of "ERR_INPUT_REJECTED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_REJECTED = 781453474u;
    // Eine Aufnahme ist VOLL und nimmt nichts mehr an, und der Vorgang endet. Abgrenzung zu
    // RESOURCE_UNAVAIL: dort ist die Ressource nicht zu belegen, hier ist sie belegt und
    // arbeitet - ihr fehlt nur der Platz. Die WRN-Haelfte gilt, wo etwas verworfen wird und
    // der Durchlauf weitergeht. BEDINGUNG - OHNE SIE IST DIE KATEGORIE EINE BEHAUPTUNG UEBER
    // FREMDEN CODE: sie gilt NUR, wo der AUFGERUFENE Verwalter selbst eine Obergrenze FUEHRT -
    // ein festes Array, ein Kapazitaetsfeld, eine full()-Abfrage. Eine Vergabe OHNE Fehlerpfad
    // kann nicht voll sein; ihr Ungueltig-Wert heisst 'nicht zu haben', und dort gilt
    // RESOURCE_UNAVAIL. Gemessen: ReplicationPstResourceManager und
    // ReplicationLodResourceManager fuehren seit dem Umbau auf mitwachsende Maps KEINE
    // Obergrenze mehr, ihre Vergabe traegt keinen Fehlerpfad - jede CAPACITY_REACHED-Zeile
    // ueber ihnen ist falsch. GEGENBEISPIELE, DIE DIE KATEGORIE BEHALTEN, und sie sind
    // wichtiger als die Regel: ReplicaSklPrivResourceManager (feste Tabelle mit TABLE_MASK)
    // und das feste Staging-Array in ReplicaCapNodeRowSystem. Pauschal zu ersetzen ist
    // derselbe Fehler wie die falsche Kategorie, nur in der Gegenrichtung. DER LEHRFALL:
    // replica_skl_sign_sys.cpp traegt beide Faelle in DERSELBEN Funktion, wenige Zeilen
    // auseinander, mit fast demselben Kommentar - der Signoff gegen die feste Tabelle behaelt
    // die Kategorie, die Slot-Vergabe daneben nicht. Kein Tor kann das trennen, weil beide
    // Zeilen gleich aussehen; nur wer den aufgerufenen Verwalter aufschlaegt, entscheidet
    // richtig.
    // FNV-1a of "ERR_CAPACITY_REACHED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t CAPACITY_REACHED = 591166716u;
    // Ein BEZEICHNER ist unbekannt: ein Name, ein Schluessel, eine Kennung, die in keinem
    // Register steht. Abgrenzung zu REFERENCE_UNRESOLVED: dort ist der Verweis wohlgeformt und
    // sein ZIEL fehlt, hier ist schon der Bezeichner selbst nicht bekannt. Und nicht
    // CONFIG_MISSING: dort ist ein Wert nicht GESETZT, hier ist er gesetzt und nicht
    // AUFLOESBAR.
    // FNV-1a of "ERR_UNKNOWN_ID" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t UNKNOWN_ID = 1384781171u;
    // Ein GELIEHENER Puffer reicht nicht. Der Unterschied zu allen drei Nachbarn ist der
    // EIGENTUEMER: INPUT_TOO_LARGE misst die Eingabe gegen eine EIGENE Obergrenze,
    // CAPACITY_REACHED eine EIGENE volle Aufnahme, RESOURCE_UNAVAIL eine nicht belegbare
    // Ressource. Hier gehoert die Grenze dem AUFRUFER, und nur er kann sie aendern - deshalb
    // schickt der Hilfetext dorthin.
    // FNV-1a of "ERR_BUFFER_TOO_SMALL" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t BUFFER_TOO_SMALL = 3518846662u;
    // Zwei Seiten erwarten verschiedene Staende: ein Modul-ABI, ein Rahmenformat, ein
    // Manifest. Nicht VALUE_INVALID - beide Werte sind fuer sich gueltig, nur zueinander
    // nicht. Die Zeile traegt IMMER beide Angaben; eine allein macht den Befund unbrauchbar,
    // weil nicht erkennbar ist, welche Seite nachzuziehen ist.
    // FNV-1a of "ERR_VERSION_MISMATCH" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VERSION_MISMATCH = 2621321880u;
    // Spiegel von WRN::CAT::VALUE_OUT_OF_RANGE auf Fehlerebene: der Wert existiert und liegt
    // ausserhalb seines gueltigen Bereichs, und der Vorgang ENDET. Auf der Warnebene
    // entscheidet der Aufrufer noch zwischen klemmen, ablehnen und behalten; hier ist die
    // Entscheidung gefallen.
    // FNV-1a of "ERR_VALUE_OUT_OF_RANGE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VALUE_OUT_OF_RANGE = 1427458957u;
    // Spiegel von WRN::CAT::VALUE_NEGATIVE auf Fehlerebene. Eigene Kategorie und nicht
    // VALUE_OUT_OF_RANGE, weil ein negativer Wert fast immer eine andere Ursache hat als ein
    // zu grosser: eine Unterlaufrechnung statt einer verletzten Obergrenze.
    // FNV-1a of "ERR_VALUE_NEGATIVE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VALUE_NEGATIVE = 847810772u;
    // Spiegel von WRN::CAT::VALUE_INVALID auf Fehlerebene: der Wert ist vorhanden und
    // semantisch ungueltig, und der Vorgang endet. Nicht VERSION_MISMATCH - dort sind beide
    // Werte fuer sich gueltig und nur zueinander nicht.
    // FNV-1a of "ERR_VALUE_INVALID" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VALUE_INVALID = 4098698602u;
}  // namespace CAT
}  // namespace ERR

namespace WRN {
namespace CAT {
    // Die ausdrueckliche Nicht-Aussage, Spiegel von ERR::CAT::UNKNOWN. NICHT der Rueckfall -
    // den traegt seit dem Hash-Umbau die laute Marke im Getter.
    // FNV-1a of "WRN_UNKNOWN" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t UNKNOWN = 123910011u;
    // KEINE Zusage ueber den Kontrollfluss. Der frueher hier stehende Satz behauptete, was
    // NACH der Meldung geschieht - eine Bereichspruefung, die NICHT klemmt, fiel dadurch
    // faelschlich durch.
    // FNV-1a of "WRN_VALUE_OUT_OF_RANGE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VALUE_OUT_OF_RANGE = 2232737799u;
    // Dieselbe Klasse wie VALUE_OUT_OF_RANGE: die Kategorie stellt den ZUSTAND fest, der
    // Aufrufer entscheidet die Reaktion.
    // FNV-1a of "WRN_VALUE_NEGATIVE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VALUE_NEGATIVE = 4268960282u;
    // Wert vorhanden, semantisch ungueltig.
    // FNV-1a of "WRN_VALUE_INVALID" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VALUE_INVALID = 3460838032u;
    // Foreign caller sent something unserviceable. Der Durchlauf geht weiter - das ist der
    // einzige Unterschied zu ERR::CAT::INPUT_REJECTED.
    // FNV-1a of "WRN_INPUT_REJECTED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_REJECTED = 3358157872u;
    // Eine Aufnahme ist VOLL und hat deshalb etwas verworfen. Abgrenzung zu RESOURCE_UNAVAIL:
    // die Ressource ist erreichbar und arbeitet - sie hat nur keinen Platz mehr. Der
    // Unterschied steht in zwei benachbarten Zeilen einer Datei (edge_keycard_routes.cpp:
    // 'queue unavailable' gegen 'queue full'). DIESELBE BEDINGUNG WIE AUF DER ERR-EBENE, und
    // sie ist hier genauso bindend: die Kategorie gilt NUR, wo der aufgerufene Verwalter
    // selbst eine Obergrenze FUEHRT. Eine Vergabe ohne Fehlerpfad kann nicht voll sein - dort
    // gilt RESOURCE_UNAVAIL. Die ausgeschriebene Fassung mit Belegen und Gegenbeispielen steht
    // unter ERR::CAT::CAPACITY_REACHED und gilt fuer beide Haelften.
    // FNV-1a of "WRN_CAPACITY_REACHED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t CAPACITY_REACHED = 3337788410u;
    // Wie ERR::CAT::WORK_PRECLUDED, aber auf Warnebene: der Durchlauf geht weiter. Ein
    // Lebenszyklus-Waechter ('existiert bereits, ueberspringe') gehoert hierher, nicht in den
    // Fehlerstrom - nichts ist kaputt. UND DIESELBE BEDINGUNG: der Hilfetext schliesst
    // 'unerreichbar' aus, eine fehlgeschlagene Slot-Vergabe ist genau das, und dort gilt
    // RESOURCE_UNAVAIL statt dieser Kategorie.
    // FNV-1a of "WRN_WORK_PRECLUDED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t WORK_PRECLUDED = 377373899u;
    // Der VERWEIS ist wohlgeformt, das Ziel existiert in der aktuellen Struktur nicht. Nicht
    // COMPONENT_MISSING (die Entity ist vollstaendig), nicht INVALID_ENTITY (nichts ist
    // zerstoert), nicht VALUE_INVALID (die Adresse ist gueltig, sie benennt nur nichts). Es
    // ist eine NACHGELAGERTE Beobachtung - der Hilfetext schickt den Leser deshalb zum
    // ERZEUGER der Adresse, nicht zum Aufrufer.
    // FNV-1a of "WRN_REFERENCE_UNRESOLVED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t REFERENCE_UNRESOLVED = 1512455874u;
    // Wie ERR::CAT::HOST_OP_FAILED, aber der Durchlauf geht weiter: ein Waechter liess sich
    // nicht scharfschalten, eine Datei nicht rotieren, ein Hilfsprogramm nicht starten - und
    // das System arbeitet mit eingeschraenkter Faehigkeit weiter. Auch der Vorgang auf einem
    // FREMDEN Wirtssystem zaehlt hierher, wenn die ausfuehrende Einheit ANTWORTET und ihre
    // Antwort einen Fehlschlag meldet: der Bittsteller hat dann ein vollstaendiges negatives
    // Ergebnis statt gar keines, die Arbeitseinheit wird fertig. Der Unterschied zur
    // ERR-Haelfte ist NICHT die Schwere des Fehlschlags, sondern ob danach noch etwas
    // passiert.
    // FNV-1a of "WRN_HOST_OP_FAILED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t HOST_OP_FAILED = 3977958947u;
    // Eine OPTIONALE Eingabe fehlt, und der Vorgang laeuft mit reduziertem Ergebnis WEITER.
    // Die Abgrenzung ist scharf gegen alle vier Nachbarn: WORK_PRECLUDED heisst, die Arbeit
    // findet NICHT statt - hier findet sie statt. INPUT_REJECTED heisst, die Anfrage wird
    // abgewiesen - hier wird sie angenommen. INPUT_TRUNCATED heisst, die Eingabe bricht ab und
    // liefert keinen Teilerfolg - hier ist sie vollstaendig, nur ein optionaler Teil fehlt.
    // VALUE_INVALID heisst, ein Wert ist ungueltig - hier ist seine Abwesenheit erlaubt.
    // FNV-1a of "WRN_INPUT_INCOMPLETE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_INCOMPLETE = 2566051898u;
    // Wie ERR::CAT::RESOURCE_UNAVAIL, aber der Durchlauf geht weiter. Die Abgrenzung zu
    // WRN::CAT::HOST_OP_FAILED ist die scharfe: dort ist ein Vorgang GESCHEITERT (der Aufruf
    // lief und schlug fehl), hier war die Ressource von vornherein nicht da. Ein leeres
    // Verzeichnis, das es nicht gibt, ist kein gescheitertes opendir - es ist ein fehlendes
    // Ziel. DIESELBE BEDINGUNG WIE AUF DER ERR-EBENE, und sie zeigt in die Gegenrichtung von
    // CAPACITY_REACHED: hierher gehoert die fehlgeschlagene Slot-Vergabe eines Verwalters OHNE
    // Obergrenze, weil der Ungueltig-Wert der Kennung 'nicht zu haben' bedeutet und nicht
    // 'voll'. ZUERST DER GEGENFALL: fuehrt der aufgerufene Verwalter einen ECHTEN Deckel -
    // festes Array, Kapazitaetsfeld, full()-Abfrage -, gilt WRN::CAT::CAPACITY_REACHED und
    // NICHT diese Kategorie; ReplicaSklPrivResourceManager und das feste Staging-Array in
    // ReplicaCapNodeRowSystem sind die belegten Beispiele. Erst wo die Vergabe KEINEN
    // Fehlerpfad traegt - ReplicationPstResourceManager, ReplicationLodResourceManager -, ist
    // diese Kategorie richtig. Die ausgeschriebene Pruefung steht unter
    // ERR::CAT::CAPACITY_REACHED und gilt fuer beide Ebenen.
    // FNV-1a of "WRN_RESOURCE_UNAVAIL" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t RESOURCE_UNAVAIL = 2021511390u;
    // Wie ERR::CAT::BUFFER_TOO_SMALL, aber der Durchlauf geht weiter - abgeschnitten oder
    // uebersprungen statt abgebrochen. Die Grenze gehoert dem AUFRUFER: das unterscheidet die
    // Kategorie von INPUT_TOO_LARGE (eigene Obergrenze) und CAPACITY_REACHED (eigene volle
    // Aufnahme), und nur deshalb schickt der Hilfetext den Leser nach draussen.
    // FNV-1a of "WRN_BUFFER_TOO_SMALL" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t BUFFER_TOO_SMALL = 1604536532u;
    // Eine wirksame ABWEICHUNG vom Vorgabewert, gemeldet damit sie in einer Fehlersuche nicht
    // uebersehen wird. Nichts ist kaputt: der Wert ist gueltig (also kein VALUE_INVALID), er
    // wurde angenommen (also kein INPUT_REJECTED), und es fehlt nichts (also kein
    // CONFIG_MISSING). Die Zeile existiert, weil eine Abweichung, die NICHT gemeldet wird,
    // jede spaetere Messung still verfaelscht - wer eine Taktrate misst, waehrend eine
    // DEV-Ueberschreibung sie setzt, misst die Ueberschreibung.
    // FNV-1a of "WRN_OVERRIDE_ACTIVE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t OVERRIDE_ACTIVE = 2157288214u;
    // Wie ERR::CAT::HUB_NOT_FOUND, aber der Durchlauf geht weiter. Der haeufige Fall ist ein
    // Leser, der vor seinem Erzeuger laeuft und beim naechsten Takt bedient wird - als Fehler
    // gemeldet fuellt er den Fehlerstrom mit einem Zustand, der sich von selbst aufloest.
    // FNV-1a of "WRN_HUB_NOT_FOUND" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t HUB_NOT_FOUND = 1442744911u;
    // Wie ERR::CAT::HUB_GLOBAL_MISSING, aber der Durchlauf geht weiter. KEIN Zusatz im suffix:
    // der Zusatz ' (GLOBAL)' gehoert der ERR-Haelfte, weil er dort aus dem Formatstring einer
    // bestimmten Stelligkeit stammt - hier waere er eine Nachahmung ohne Herkunft.
    // FNV-1a of "WRN_HUB_GLOBAL_MISSING" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t HUB_GLOBAL_MISSING = 3265572123u;
    // Wie ERR::CAT::COMPONENT_MISSING, aber die Schleife laeuft weiter. Der Unterschied ist
    // wichtiger als er aussieht: eine Entity ohne Component in einer Iteration ueber tausend
    // ist ein uebersprungener Einzelfall, kein gescheiterter Durchlauf. Nicht zu verwechseln
    // mit einer WIRKLICH optionalen Component - deren Abwesenheit ist erlaubt und wird gar
    // nicht gemeldet.
    // FNV-1a of "WRN_COMPONENT_MISSING" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t COMPONENT_MISSING = 59028729u;
    // Wie ERR::CAT::MANAGER_ABSENT, aber der Durchlauf geht weiter. Beide Ebenen werden
    // gebraucht und die Wahl haengt am Kontrollfluss der Fundstelle, nicht an ihrer Schwere:
    // wo das System hinter der Pruefung zurueckkehrt, ist es ERR, wo es die naechste Einheit
    // nimmt und weitermacht, ist es WRN. Die Abgrenzung gegen COMPONENT_MISSING,
    // INVALID_ENTITY, REFERENCE_UNRESOLVED, RESOURCE_UNAVAIL und HUB_NOT_FOUND steht
    // ausgeschrieben unter ERR::CAT::MANAGER_ABSENT und gilt hier unveraendert.
    // FNV-1a of "WRN_MANAGER_ABSENT" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t MANAGER_ABSENT = 410794518u;
    // Wie ERR::CAT::INVALID_ENTITY, aber der Durchlauf geht weiter. Nicht
    // REFERENCE_UNRESOLVED: dort ist der Verweis wohlgeformt und sein Ziel fehlt, hier ist
    // schon die Kennung selbst ungueltig.
    // FNV-1a of "WRN_INVALID_ENTITY" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INVALID_ENTITY = 3953671656u;
    // Wie ERR::CAT::SCHEDULE_ORDER, aber der Takt laeuft weiter. Der Regelfall auf dieser
    // Ebene ist eine Reihenfolge, die nur NICHT ZUGESICHERT ist: ohne run_after-Kante ordnet
    // die Registrierungsreihenfolge, und das haelt in der Praxis, bis jemand eine
    // Registrierung verschiebt.
    // FNV-1a of "WRN_SCHEDULE_ORDER" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t SCHEDULE_ORDER = 1974783417u;
    // Wie ERR::CAT::CONFIG_MISSING, aber der Durchlauf geht weiter, weil ein Vorgabewert
    // einspringt. Die Zeile ist gerade DANN wichtig: ein stiller Vorgabewert sieht in jeder
    // spaeteren Messung wie eine bewusste Einstellung aus.
    // FNV-1a of "WRN_CONFIG_MISSING" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t CONFIG_MISSING = 336737590u;
    // Wie ERR::CAT::INPUT_TOO_LARGE, aber der Durchlauf geht weiter. Die Abgrenzung zu
    // BUFFER_TOO_SMALL ist der EIGENTUEMER der Grenze: hier ist es die eigene dokumentierte
    // Obergrenze, dort ein vom Aufrufer gelieferter Puffer.
    // FNV-1a of "WRN_INPUT_TOO_LARGE" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_TOO_LARGE = 464467204u;
    // Wie ERR::CAT::INPUT_TRUNCATED, aber der Durchlauf geht weiter. Der typische Ort ist eine
    // Empfangsschleife: ein zu kurzer Rahmen wird verworfen, die Verbindung bleibt bestehen
    // und der naechste Rahmen wird gelesen.
    // FNV-1a of "WRN_INPUT_TRUNCATED" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t INPUT_TRUNCATED = 2766296556u;
    // Wie ERR::CAT::UNKNOWN_ID, aber der Durchlauf geht weiter. Haeufig beim Einlesen fremder
    // Daten: ein unbekannter Schluessel wird uebersprungen, die uebrigen werden verarbeitet.
    // FNV-1a of "WRN_UNKNOWN_ID" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t UNKNOWN_ID = 2224052385u;
    // Wie ERR::CAT::VERSION_MISMATCH, aber der Durchlauf geht weiter, meist mit
    // eingeschraenkter Faehigkeit. Wie dort traegt die Zeile IMMER beide Angaben - eine allein
    // sagt nicht, welche Seite nachzuziehen ist.
    // FNV-1a of "WRN_VERSION_MISMATCH" - the NAMESPACE is part of the
    // hashed string, so the mirrored halves are two distinct values.
    constexpr uint32_t VERSION_MISMATCH = 810769522u;
}  // namespace CAT
}  // namespace WRN

namespace detail {
    // NO counter and NO pinned-id asserts - both were artefacts of the table
    // scheme. A constant is now the hash of its own name, so it cannot shift
    // when a neighbour is inserted or removed: the protection is structural
    // instead of asserted. What CAN still go wrong is a hash collision inside
    // one namespace, and that is caught in the generator, where it can name
    // both categories - a static_assert here could only say that two numbers
    // differ.
    //
    // Defined in log_err_cat_gen.cpp. Header-only consumers link against
    // ase::log or resolve these at dlopen time (RTLD_GLOBAL), the same way
    // log_cat_gen.cpp is already consumed by 105 modules and plugins.
    const char* get_cat_name(uint32_t cat);
    const char* get_cat_help(uint32_t cat);
    const char* get_cat_suffix(uint32_t cat);
    const char* get_wrn_cat_name(uint32_t cat);
    const char* get_wrn_cat_help(uint32_t cat);
    // Die SHORT-Texte derselben SSOT: die Essenz, die log.hpp ans Zeilenende haengt.
    const char* get_cat_short(uint32_t cat);
    const char* get_wrn_cat_short(uint32_t cat);
    // Der TAIL ist der hint als EIGENE physische Zeile: Newline, Einzug aus der
    // Anzeige-Politik, dann der Rat - sonst nichts. Das Paar ist EIN Datensatz, ein
    // hint steht nie ohne seinen Kopf direkt darueber; eine eigene Marke waere die
    // Wiederholung dessen, was der Kopf schon sagt. Leer, wenn die Kategorie keinen
    // hint fuehrt - die Meldung bleibt dann einzeilig. log.hpp haengt ihn als letztes
    // Argument an; damit traegt JEDER Kanal denselben zweizeiligen Datensatz.
    const char* get_cat_tail(uint32_t cat);
    const char* get_wrn_cat_tail(uint32_t cat);
}  // namespace detail

}  // namespace ase::log
