#pragma once

/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 * 
 * Generated by: core/core/ase-log/scripts/gen_log_cat.py
 * Source: core/core/ase-validator/ecs_validator/data/taxonomy/*.json
 * 
 * SMALL HEADER - safe to include everywhere.
 * Big switch (7144 cases) is in log_cat_gen.cpp.
 * 
 * Total categories: 7144
 * Bit-array chunks: 112 (64 bits each)
 */

#include <atomic>
#include <cstdint>

namespace ase::log::filter {

// ============================================================================
// Constants
// ============================================================================

constexpr int CATEGORY_COUNT = 7144;
constexpr int CHUNK_COUNT = 112;

// ============================================================================
// Log Levels (bitmask)
// ============================================================================

constexpr uint8_t LVL_TRC = 0x01;  // Trace
constexpr uint8_t LVL_DBG = 0x02;  // Debug
constexpr uint8_t LVL_INF = 0x04;  // Info
constexpr uint8_t LVL_WRN = 0x08;  // Warn
constexpr uint8_t LVL_ERR = 0x10;  // Error
constexpr uint8_t LVL_CRT = 0x20;  // Critical
constexpr uint8_t LVL_ALL = 0x3F;  // All levels

// ============================================================================
// Category Bit-Array (scalable to unlimited categories)
// ============================================================================

struct CategoryMask {
    uint64_t chunks[CHUNK_COUNT] = {};
    
    void set(int bit_pos);
    bool intersects(const CategoryMask& other) const;
};

// ============================================================================
// Runtime Filter State (defined in log_cat_gen.cpp)
// ============================================================================

extern std::atomic<uint8_t> g_level_mask;
extern CategoryMask g_blocked_categories;

// ============================================================================
// Client Filter State (defined in log_cat_gen.cpp)
// ============================================================================

extern std::atomic<uint64_t> g_client_mask;      ///< Whitelist (0 = all pass)
extern std::atomic<uint64_t> g_blocked_clients;   ///< Blacklist bitmask

// ============================================================================
// Function Declarations (implemented in log_cat_gen.cpp)
// ============================================================================

/// Hash abbreviation to bit position (-1 if not found)
int abbrev_to_bit(uint32_t hash);

/// Extract categories from filename
CategoryMask file_to_categories(const char* file);

/// Check if log should be emitted
bool should_log(uint8_t level, const CategoryMask& file_cats);

/// Check if client log should be emitted (level + category + client filter)
bool should_log_client(uint8_t level, const CategoryMask& file_cats, uint64_t client_bit);

/// Parse CLI filter string (e.g., "+INF +WRN -BCT +CLT:01")
void parse_log_filter(const char* filter_str);

}  // namespace ase::log::filter
