#pragma once

/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 * 
 * Generated by: core/ase-log/scripts/gen_log_cat.py
 * Source: taxonomy/ + hub_constants.json + hub_metrics.json + hub_tags.json
 * 
 * SMALL HEADER - safe to include everywhere.
 * Init table + libcuckoo engine is in log_cat_gen.cpp.
 * 
 * Capacity: 16384 categories, 256 chunks (64 bits each)
 * FIXED size - adding categories only changes log_cat_gen.cpp, not this header.
 */

#include <atomic>
#include <cstdint>

namespace ase::log::filter {

// ============================================================================
// Constants (FIXED - do not change! Only .cpp changes when categories grow)
// ============================================================================

constexpr int CATEGORY_COUNT = 16384;
constexpr int CHUNK_COUNT = 256;

// ============================================================================
// Log Levels (bitmask)
// ============================================================================

constexpr uint8_t LVL_TRC = 0x01;  // Trace
constexpr uint8_t LVL_DBG = 0x02;  // Debug
constexpr uint8_t LVL_INF = 0x04;  // Info
constexpr uint8_t LVL_WRN = 0x08;  // Warn
constexpr uint8_t LVL_ERR = 0x10;  // Error
constexpr uint8_t LVL_CRT = 0x20;  // Critical
constexpr uint8_t LVL_ALL = 0x3F;  // All levels

// ============================================================================
// Category Bit-Array (scalable to unlimited categories)
// ============================================================================

struct CategoryMask {
    uint64_t chunks[CHUNK_COUNT] = {};
    
    void set(int bit_pos);
    bool intersects(const CategoryMask& other) const;
};

// ============================================================================
// Runtime Filter State (defined in log_cat_gen.cpp)
// ============================================================================

extern std::atomic<uint8_t> g_level_mask;
extern CategoryMask g_blocked_categories;
extern CategoryMask g_whitelisted_categories;  ///< Whitelist (empty = all pass)
extern std::atomic<bool> g_has_whitelist;       ///< True if any +CATEGORY was set

// ============================================================================
// Client Filter State (defined in log_cat_gen.cpp)
// ============================================================================

extern std::atomic<uint64_t> g_client_mask;      ///< Whitelist (0 = all pass)
extern std::atomic<uint64_t> g_blocked_clients;   ///< Blacklist bitmask

// ============================================================================
// Function Declarations (implemented in log_cat_gen.cpp)
// ============================================================================

/// Hash abbreviation to bit position (-1 if not found)
int abbrev_to_bit(uint32_t hash);

/// Extract categories from filename (tokenizes at _ . separators)
CategoryMask file_to_categories(const char* file);

/// Extract categories from function name (tokenizes at :: _ ( ) , space &)
CategoryMask func_to_categories(const char* func);

/// Parse CLI filter string (e.g., "+INF +WRN -BCT +EPH +TICK +CLT:01")
void parse_log_filter(const char* filter_str);

/// O(1) cached filter check for file+function (~12 cycles hot path)
bool should_log_loc(uint8_t level, const char* file, const char* func);

/// O(1) cached filter check for client file+function
bool should_log_client_loc(uint8_t level, const char* file, const char* func, uint64_t client_bit);

/// Invalidate location cache (call after filter changes)
void invalidate_loc_cache();

}  // namespace ase::log::filter
