#pragma once

/**
 * ASE CORE INFRASTRUCTURE HEADER
 *
 * AUTO-GENERATED FILE - DO NOT EDIT!
 * Edit core/ase-log/scripts/gen_log_cat.py and run it instead. A hand
 * fix here survives exactly until the next generator run.
 *
 * @file        log_cat_gen.hpp
 * @brief       Category bit positions and the runtime log filter state
 * @description Declarations only: one bit per taxonomy category, the mask
 *              type that holds them, and the filter state the log macros
 *              read on every call. The init table and the libcuckoo engine
 *              live in log_cat_gen.cpp so this header stays cheap to
 *              include everywhere.
 *
 * @module      ase-log
 * @layer       1 (Core)
 * @category    ecs/module
 * @created     2026-01-09
 * @modified    2026-08-20
 * @version     1.1.0
 *
 * CORE INFRASTRUCTURE COMPLIANCE
 *
 * [ ] NOT an ECS Component or System
 * [ ] Layer dependencies correct (L0: no ASE deps, L1: L0 only)
 * [ ] No global mutable state (constexpr/const only)
 * [ ] No singletons or static mutable variables
 * [ ] Thread-safe by design (pure functions or explicit mutex)
 * [ ] All public functions documented with @brief, @param, @return
 * [ ] constexpr where possible (compile-time evaluation)
 * [ ] noexcept where possible (no-throw guarantee)
 * [ ] [[nodiscard]] on functions returning values
 * [ ] No magic numbers (use named constants)
 * [ ] No implicit conversions (use explicit constructors)
 * [ ] Header-only OR header+cpp pattern (not mixed)
 * [ ] Include guards via #pragma once
 * [ ] Namespace matches module: ase::{module}
 * [ ] No circular dependencies
 * [ ] No macros (except include guards) - use constexpr/templates
 * [ ] API stable (changes require version bump)
 * 
 * Generated by: core/ase-log/scripts/gen_log_cat.py
 * Source: taxonomy/ + hub_constants.json + hub_metrics.json + hub_tags.json
 * 
 * SMALL HEADER - safe to include everywhere.
 * Init table + libcuckoo engine is in log_cat_gen.cpp.
 * 
 * Capacity: 16384 categories, 256 chunks (64 bits each)
 * FIXED size - adding categories only changes log_cat_gen.cpp, not this header.
 */

#include <atomic>
#include <cstdint>

namespace ase::log::filter {

// ============================================================================
// Constants (FIXED - do not change! Only .cpp changes when categories grow)
// ============================================================================

constexpr int CATEGORY_COUNT = 16384;
constexpr int CHUNK_COUNT = 256;

// ============================================================================
// Log Levels (bitmask)
// ============================================================================

constexpr uint8_t LVL_TRC = 0x01;  // Trace
constexpr uint8_t LVL_DBG = 0x02;  // Debug
constexpr uint8_t LVL_INF = 0x04;  // Info
constexpr uint8_t LVL_WRN = 0x08;  // Warn
constexpr uint8_t LVL_ERR = 0x10;  // Error
constexpr uint8_t LVL_CRT = 0x20;  // Critical
constexpr uint8_t LVL_ALL = 0x3F;  // All levels

// ============================================================================
// Category Bit-Array (scalable to unlimited categories)
// ============================================================================

struct CategoryMask {
    uint64_t chunks[CHUNK_COUNT] = {};
    
    void set(int bit_pos);
    bool intersects(const CategoryMask& other) const;
};

// ============================================================================
// Runtime Filter State (defined in log_cat_gen.cpp)
// ============================================================================
//
// ACCESSORS, NOT FREE GLOBALS (changed 2026-08-20). These six pieces of state used
// to be `extern` variables. Two reasons for the accessor form, and the rule finding
// is only the second one:
//
//   1. STATIC INITIALISATION ORDER. should_log_loc() reads the level mask on EVERY
//      log call, from every translation unit in the tree - including ones whose own
//      static initialisation runs BEFORE this file's. A free global read at that
//      moment is a read of an uninitialised object. A function-local static is
//      initialised on first call instead, which is exactly when it is needed. This
//      module has already paid for the neighbouring version of that problem once:
//      log_sys.cpp::on_stop carries a long comment about merged statics being freed
//      twice at exit.
//   2. CONSISTENCY INSIDE THIS VERY FILE. loc_cache() and abbrev_map() are already
//      built this way, by this same generator. Two shapes for the same job in one
//      generated file is not a decision, it is a leftover.

std::atomic<uint8_t>& level_mask();
CategoryMask& blocked_categories();
CategoryMask& whitelisted_categories();  ///< Whitelist (empty = all pass)
std::atomic<bool>& has_whitelist();      ///< True if any +CATEGORY was set

// ============================================================================
// Client Filter State (defined in log_cat_gen.cpp)
// ============================================================================

std::atomic<uint64_t>& client_mask();     ///< Whitelist (0 = all pass)
std::atomic<uint64_t>& blocked_clients();  ///< Blacklist bitmask

// ============================================================================
// Function Declarations (implemented in log_cat_gen.cpp)
// ============================================================================

/// Hash abbreviation to bit position (-1 if not found)
int abbrev_to_bit(uint32_t hash);

/// Extract categories from filename (tokenizes at _ . separators)
CategoryMask file_to_categories(const char* file);

/// Extract categories from function name (tokenizes at :: _ ( ) , space &)
CategoryMask func_to_categories(const char* func);

/// Parse CLI filter string (e.g., "+INF +WRN -BCT +EPH +TICK +CLT:01")
void parse_log_filter(const char* filter_str);

/// O(1) cached filter check for file+function (~12 cycles hot path)
// The location key is computed at the CALL SITE (log::loc_key, constexpr-folded), not
// here: hashing the two strings per call would multiply the fast path this cache exists
// to avoid. Until 2026-08-22 the key came from reinterpret_cast on the two POINTERS —
// forbidden, and unstable across translation units where identical __FILE__ literals
// may sit at different addresses.
bool should_log_loc(uint8_t level, const char* file, const char* func, uint64_t key);

/// O(1) cached filter check for client file+function
bool should_log_client_loc(uint8_t level, const char* file, const char* func, uint64_t key,
                           uint64_t client_bit);

/// Invalidate location cache (call after filter changes)
void invalidate_loc_cache();

}  // namespace ase::log::filter
